// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfb9TKI8qZqz7tItTQxlP6xzSLJdVW7Dk',
    appId: '1:351176125861:web:7a84c3ce030d03da9f8c4c',
    messagingSenderId: '351176125861',
    projectId: 'coastal-5892d',
    authDomain: 'coastal-5892d.firebaseapp.com',
    storageBucket: 'coastal-5892d.appspot.com',
    measurementId: 'G-XFT5BJLVXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpklX3AcMWlunoDgMQplU6DiKCyUR2YqE',
    appId: '1:351176125861:android:91996b39591804089f8c4c',
    messagingSenderId: '351176125861',
    projectId: 'coastal-5892d',
    storageBucket: 'coastal-5892d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq_lqdVe1bUyeLgUK5Uit_nBRgZyfhdWg',
    appId: '1:351176125861:ios:2b47f9ab830f13959f8c4c',
    messagingSenderId: '351176125861',
    projectId: 'coastal-5892d',
    storageBucket: 'coastal-5892d.appspot.com',
    androidClientId: '351176125861-490cfuc0acaoprvm9c43t0r5lb5jpcvc.apps.googleusercontent.com',
    iosClientId: '351176125861-633k1017cg0qp578m6i6ut6sushu322h.apps.googleusercontent.com',
    iosBundleId: 'com.example.coastal',
  );
}
